### ISSUE TITLE
GRPC Compression in transmission 

### ISSUE THREAD

**Issue by prmanna** [openconfig/gnmi#112]
Hi,

Is compression used in the transmission? 
As GRPC supports compression, does GNMI use this to reduce bandwidth in transmission, especially for streaming?

Thanks,
Prasenjit Manna

**Comment by hellt** [comment]
Hi @prmanna 
you can configure compression on a grpc channel 
gnmi is agnostic to that

for example, here is a go example of a gnmi client that uses compression on a grpc channel https://github.com/karimra/gnmic/pull/351

**Comment by prmanna** [comment]
Thanks @hellt
