### ISSUE TITLE
Publishing releases for the different gnmi versions

### ISSUE THREAD

**Issue by pedroaston** [openconfig/gnmi#130]
Hello there! I've recently started using gnmi protos with several vendor's routers in an ISP context. One thing that would agilize a lot my work would be to publish releases of the different proto versions, since that depending on the manufacturer, and the software version of the devices, they may support one or other.

Currently I'm downgrading the master branch to specific commits, but for future sake I think it would benefit everyone having the gnmi releases published. Is there any reason for currently not doing this?

PS: The same can be said about the reference repo. At the time of writing nokia and cisco support gnmi v0.7.0

Thanks in advance 😄

**Comment by marcushines** [comment]
fixed
