### ISSUE TITLE
Alternative to SubscribeResponse_Error

### ISSUE THREAD

**Issue by sspaink** [openconfig/gnmi#132]
The type `SubscribeResponse_Error` has been marked as deprecated https://github.com/openconfig/gnmi/blob/480bf53a74d21bb0a82d5d716264874de1070120/proto/gnmi/gnmi.pb.go#L1372-L1375

We are using this type to report the error code and message, but it isn't clear how the suggested package `google.golang.org/genproto/googleapis/rpc/status` should be used instead. Could someone please suggest the correct way to fix this? There doesn't seem a way to get the rpc status from the reply?

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/gnmi/gnmi.go#L315-L322
```go
func (c *GNMI) handleSubscribeResponse(worker *Worker, reply *gnmiLib.SubscribeResponse) {
	switch response := reply.Response.(type) {
	case *gnmiLib.SubscribeResponse_Update:
		c.handleSubscribeResponseUpdate(worker, response)
	case *gnmiLib.SubscribeResponse_Error:
		c.Log.Errorf("Subscribe error (%d), %q", response.Error.Code, response.Error.Message) //nolint:staticcheck
	}
}
```

**Comment by gcsl** [comment]
The RPC status message does not appear in the application level message.  Rather it is returned as the error, in this case for a stream.Recv() call here.

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/gnmi/gnmi.go#L303
