### ISSUE TITLE
-timeout option does not work for me.

### ISSUE THREAD

**Issue by chuansir** [openconfig/gnmi#14]
Try to use shorter timeout period for debug purpose. But it failed.

**Comment by awly** [comment]
Could you show the full command you were running and what exactly is expected to time out?
This timeout only applies to establishing the connection. It can take a lot of time after connecting to stream the actual data, and that will not time out.

**Comment by gcsl** [comment]
Per Andrew's comment, if you use the -display_type=single  (or -dt=s for
short) or -dt=proto (-dt=p) this will render the data as it comes in
instead of building the whole of the pre-sync responses into a single tree
before rendering.

**Comment by awly** [comment]
Ping @chuansir
