### ISSUE TITLE
Question regarding Alias field

### ISSUE THREAD

**Issue by ektanehwal** [openconfig/gnmi#167]
I was upgrading gnmi.proto 0.7.0 to 0.10.0 and I saw "Alias field" has been removed from 0.10.0 and at some places it is kept as "reserved". I had two queries in this respect: 
What's the difference b/w a deprecated field and reserved field? 
Since "Alias" has been removed from 0.10.0 proto so how this proto will be backward compatible to older gnmi.proto versions.?

Portion which is removed: 
`// Alias specifies a data tree path, and an associated string which defines an
// alias which is to be used for this path in the context of the RPC. The alias
// is specified as a string which is prefixed with "#" to disambiguate it from
// data tree element paths.
// Reference: gNMI Specification Section 2.4.2
message Alias {
  Path path = 1;     // The path to be aliased.
  string alias = 2;  // The alias value, a string prefixed by "#".
}

// AliasList specifies a list of aliases. It is used in a SubscribeRequest for
// a client to create a set of aliases that the target is to utilize.
// Reference: gNMI Specification Section 3.5.1.6
message AliasList {
  repeated Alias alias = 1;    // The set of aliases to be created.
}`

**Comment by dplore** [comment]
There is a  [gRPC proto description for the reserved field](https://protobuf.dev/programming-guides/proto3/#fieldreserved).  Reserved fields replace deleted fields.  

Deprecated means the field is still supported, but is a warning that it will be removed in a future release and that any new code should not use the field.  It is also documented above.

**Comment by dplore** [comment]
I am closing this issue because I think I answered your questions, but feel free to reopen if needed.
