### ISSUE TITLE
gnmi_cli hangs on to the host machine if the underlying putty session experience a network disconnection

### ISSUE THREAD

**Issue by ashu-ciena** [openconfig/gnmi#172]
When the gnmi_cli is run from a linux machine by logging into the machine through a putty shell from windows PC and due to network glitch, putty shell disconnects, the gnmi client continues to run in background for a while (10-15 minutes) but stops acknowledging to the gnmi notifications when the underlying transport protocol is gRPC. 

Eventually, the gRPC write at server side is stuck and all subsequent writes starts getting queued up at server side. 

The problem is, the connection is not closed instantly and hence clean up of the gNMI session does not happen till the gnmi client starts the closing sequence.  

This problem is not seen with gNMIC client.

**Comment by robshakir** [comment]
I'm not sure I understand the case here -- is the binary running on the remote side? What state `gnmi_cli` in in this case?

**Comment by ashu-ciena** [comment]
Not able to reproduce at this moment, closing for now.  Will file a new ticket if required.
