### ISSUE TITLE
Question:some minor questions about gnmi.proto

### ISSUE THREAD

**Issue by dingrui37** [openconfig/gnmi#18]
1. The gnmi.proto file is using proto3, why the generated file named with gnmi_pb2.py and gnmi_pb2_grpc.py?
`syntax = "proto3";`

2.  What's the difference bwtween gnmi_pb2.py and gnmi_pb2_grpc.py?  I think gnmi_pb2.py is enough,
why we need gnmi_pb2_grpc.py?

**Comment by robshakir** [comment]
1. Both `proto2` and `proto3` use the same file extension - `_pb2.py`, as per [this page](https://developers.google.com/protocol-buffers/docs/reference/python-generated).
2. `gnmi_pb2.py` does not include the stub definitions from the GA gRPC library. The stubs that are included in `gnmi_pb.py` will be deprecated by `protoc`, please see [this comment](https://github.com/openconfig/gnmi/blob/master/proto/gnmi/gnmi_pb2.py#L1776-L1777).

**Comment by robshakir** [comment]
Please re-open this issue if you have other questions.
