### ISSUE TITLE
Updates are either delayed or getting lost when 256 network router streaming 10K updates/20sec

### ISSUE THREAD

**Issue by kulpatel** [openconfig/gnmi#181]
Updates are either delayed or getting lost when 256 network router streaming 10K updates/20sec. I tried two case when streaming directly from devices m receiving all the updates but while getting it from gateway i m not receiving all updates on time (delayed not at 20 sec its random some time 1 min apart sometime 2 min apart ). I have changed target devices t0 300, "-TargetLimit=300". Any setting needs to to be tweaked, i have tried changing the "GatewayTransitionBufferSize" to higher value but no luck any input?

i made sure no update are same to avoid duplication and gateway not sending it.

**Comment by dplore** [comment]
Hi, @kulpatel  if you have a code change /  bug fix to submit, we'd be happy to review it.  But we don't generally attempt to reproduce and troubleshoot issues reported by the community.

**Comment by robshakir** [comment]
Please re-open if you have additional data. It's not clear that this refers to the collector in this repository.
