### ISSUE TITLE
ambiguous import when installing

### ISSUE THREAD

**Issue by gilesheron** [openconfig/gnmi#184]
when attempting to install I got this:

go: github.com/openconfig/gnmi/cmd/gnmi_cli imports
	github.com/openconfig/gnmi/proto/gnmi imports
	google.golang.org/grpc/status imports
	google.golang.org/genproto/googleapis/rpc/status: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/status in multiple modules:
	google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1 (/Users/giles/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230410155749-daa745c078e1/googleapis/rpc/status)
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240903143218-8af14fe29dc1 (/Users/giles/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20240903143218-8af14fe29dc1/status)

Following a quick google I found:

https://github.com/googleapis/go-genproto/issues/1015

following the instructions there seems to fix the problem :)

**Comment by robshakir** [comment]
Thanks! Created #185.

**Comment by dplore** [comment]
Thanks for fixing @robshakir.   Thanks again @gilesheron for reporting this.
