### ISSUE TITLE
How to fill Subscription attributes in SubscribeRequest using gnmi_cli

### ISSUE THREAD

**Issue by kboyapa1** [openconfig/gnmi#20]
We are able to fill very few attributes of SubscribeRequest-->SubscriptionList attribute like mode using --qt in gnmi_cli.

gnmi_cli help is not displaying options (_I may be missing from the list of displayed options_) to fill other SubscribeRequest attributes like poll, aliases, prefix, use_aliases, qos, encoding, sample_interval, suppress_redundant, heartbeat_interval etc...

Can Please point me some examples how to fill SubscribeRequest fields using gnmi_cli client.

**Comment by kboyapa1** [comment]
Can please advise if gnmi client is not supporting to fill all the SubscribeRequest attributes in gnmi.proto, when the support will be available?

**Comment by robshakir** [comment]
The client does not support all the options that are within the gNMI specification, as you say. We don't have a timeline for supporting all the options here. This library tends to be focused towards the implementations that we have of gNMI in the field. 

If you have a requirement for these features, we welcome pull requests against this repo. One of the maintainers can assist with reviewing such PRs.

Thanks,
r.

**Comment by kboyapa1** [comment]
Thanks @robshakir for your suggestion.
We are in the process of identifying the requirements and studying the gnmi_cli support.

We will surely share the pull requests when we make the changes.
