### ISSUE TITLE
gnmi_cli is not framing path elem correctly for a given query in SetRequest

### ISSUE THREAD

**Issue by kboyapa1** [openconfig/gnmi#23]
When the key is specified in an update/replace query for SetRequest, the key field is not populating the path elem of SetRequest. I am able to see key and value fields properly for the same query in case of SubscribeRequest.

Can please point me how to get the key and value fields properly in case of SetRequest?

Following is the SetRequest update/replace request that gnmi server received from the gnmi GO client.

update SetRequest:
==============
gnmi_cli --address localhost:50051 --ca_crt=/home/ca-bundle.crt --client_crt=/home/client.crt --client_key= /home/client.key -set -update "/eqpt/shelf[shelfId='1']/type=up"

Server Received:
update {
  path {
    element: "eqpt"
    element: "shelfId"
    elem {
      name: "eqpt"
    }
    elem {
      name: "shelfId"
    }
  }
  value {
    value: "\"\'1\']/type=up\""
  }
  val {
    json_val: "\"\'1\']/type=up\""
  }
}

replace SetRequest:
==============
gnmi_cli --address localhost:50051 --ca_crt=/home/ca-bundle.crt --client_crt=/home/client.crt --client_key= /home/client.key -set -replace "/eqpt/shelf[shelfId='1']/type=up"

Server Received:
replace {
  path {
    element: "eqpt"
    element: "shelfId"
    elem {
      name: "eqpt"
    }
    elem {
      name: "shelfId"
    }
  }
  value {
    value: "\"\'1\']/type=up\""
  }
  val {
    json_val: "\"\'1\']/type=up\""
  }
}

SubscribeRequest:
=============
gnmi_cli --address localhost:50051 --ca_crt=/home/ca-bundle.crt --client_crt=/home/client.crt --client_key= /home/client.key --q "/eqpt/shelf[shelfId='1']/type" --qt=p -pi=10s --c=1

Server Received:

subscribe {
  prefix {
  }
  subscription {
    path {
      element: "eqpt"
      element: "shelf[shelfId=\'1\']"
      element: "type"
      elem {
        name: "eqpt"
      }
      elem {
        name: "shelf"
        key {
          key: "shelfId"
          value: "\'1\'"
        }
      }
      elem {
        name: "type"
      }
    }
  }
  mode: POLL
}

**Comment by kboyapa1** [comment]
What need to be changed in the gnmi_cli to encode the xpath query properly into SetRequest Path for an update/replace?

**Comment by robshakir** [comment]
`gnmi_cli` uses the path parsing functions from ygot (github.com/openconfig/ygot). These use the format of paths that were proposed in the gNMI path specification - which do not include quotes for the keys - so you would state `/eqpt/shelf[shelfId=1]/type` rather than having the quotations in the key value.

We have a TODO to write a document that describes the text convention for these paths.

**Comment by kboyapa1** [comment]
Thanks @robshakir for your suggestion. I have removed the quotations in the key value.

I have printed the sr.Delete, sr.Update and sr.Replace for the same keypath(/eqpt/shelf[shelfId=1]/type=up) from func convertSetRequest in client.go. Following are printed values. The input (sr client.SetRequest)to Set RPC seems different. 

sr.Delete  =  [[ eqpt shelf[shelfId=1] type=up]]
sr.Update =  [{[ eqpt shelf[shelfId] 1]/type=up 0001-01-01 00:00:00 +0000 UTC}]
sr.Replace =  [{[ eqpt shelf[shelfId] 1]/type=up 0001-01-01 00:00:00 +0000 UTC}]

In case of Update/Replace SetRequest, v.Path =  [ eqpt shelf[shelfId] and v.Val =  1]/type=up

Can please point me why the Set RPC is not receiving the query properly? 
(I am new to gnmi client and not sure how gnmi client's Set RPC gets called)

**Comment by gcsl** [comment]
Get and Set have been modified to take the proto directly from the command line giving full flexibility in formulating the request.  The same flexibility has been added for Subscribe.

**Comment by kboyapa1** [comment]
Thanks @gcsl for your update. I could see the Get and Set options in the latest gnmi_cli.

Can you please help me in setting up the proto for gnmi.SetRequest in the command line for the xpath /eqpt/shelf[shelfId=1]/slot[slotID='FAN'][admin-status=down] ?

At least please point me the reference where we can get some examples for proto set up in gnmi_cli.

**Comment by kboyapa1** [comment]
I want to perform a Get operation on xpath /eqpt. I have set the gnmi.GetRequest proto as path<elem<name:"eqpt">>, I am getting following error from the gnmi_cli parser. /eqpt is a valid xpath in our system. Did I miss anything in setting up proto?

E0702 00:45:24.484458   12144 gnmi_cli.go:180] unable to parse gnmi.GetRequest from "path<elem<name:eqpt>>" : line 1.15: invalid string: eqpt

**Comment by kboyapa1** [comment]
--set --proto "update<path<elem<name:'eqpt'> elem<name:'shelf' key<key:'shelfId' value:'1'>> elem<name:'slot' key<key:'slotID' value:'FAN1'>>> val<json_val:'{"admin-status": "up"}'>>"
