### ISSUE TITLE
Regenerate .pb.go files with protoc-gen-go v1.1.0

### ISSUE THREAD

**Issue by aaronbee** [openconfig/gnmi#24]
[v1.1.0 of golang/protobuf](https://github.com/golang/protobuf/releases/tag/v1.1.0) has been released and is "1.3x to 2.1x faster". To take advantage of some of these improvements requires regenerating the .pb.go files with the latest version of protoc-gen-go.

**Comment by robshakir** [comment]
Thanks Aaron -- PR on its way.
