### ISSUE TITLE
Working example of gNMI

### ISSUE THREAD

**Issue by GoutamHub** [openconfig/gnmi#25]
I am new to gNMI, can you please provide a doc to try some working examples of gNMI.

**Comment by robshakir** [comment]
The full specification for gNMI is can be found in the [openconfig/reference](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md) repo. For code examples, you can look at the [google/gnxi](https://github.com/google/gnxi) example implementation, along with the [fake agent](https://github.com/openconfig/gnmi/blob/master/testing/fake/gnmi/agent.go) in this repo.

If you have specific questions relating to these artifacts, please raise them in the relevant repository.

Thanks,
r.
