### ISSUE TITLE
gnmi_cli command line proto setup example

### ISSUE THREAD

**Issue by kboyapa1** [openconfig/gnmi#28]
https://github.com/openconfig/gnmi/issues/23

the xpath /eqpt is a valid xpath and when i set this path elem name to gnmi.GetRequest proto (path<elem<name:"eqpt">>), getting invalid string error from gnmi_cli parser.  Can please point me what is wrong in the proto setup? Please provide some examples reference.

E0702 00:45:24.484458 12144 gnmi_cli.go:180] unable to parse gnmi.GetRequest from "path<elemname:eqpt>" : line 1.15: invalid string: eqpt

**Comment by kboyapa1** [comment]
I am able to set the path elem in proto for set operation.

--set --proto "update<path<elem<name:'eqpt'> elem<name:'shelf' key<key:'shelfId' value:'1'>> elem<name:'slot' key<key:'slotID' value:'FAN1'>>> val<json_val:'{"admin-status": "up"}'>>"

**Comment by auds79** [comment]
add me as reviewer to this PR
