### ISSUE TITLE
Question:why use bi-directional RPC in Subscribe?

### ISSUE THREAD

**Issue by VerricDr** [openconfig/gnmi#41]
Hi,all,I think the SubscribeResponse use stream is enough, why use bi-directional?

rpc Subscribe(stream SubscribeRequest) returns (stream SubscribeResponse);
}

**Comment by robshakir** [comment]
There are cases (e.g., the `POLL` mode of subscribe) where the client needs to send a message to the target to trigger data to be sent after the initial subscription is created. This was the motivation for Subscribe to be a bi-directional streaming RPC.

**Comment by VerricDr** [comment]
thanks
