### ISSUE TITLE
gNMI dial in vs dial out

### ISSUE THREAD

**Issue by medha-joshi** [openconfig/gnmi#42]
As I understand both are supported from gNMI/gRPC standard point of view. Right ? 

*** Which forum such questions should be asked ? *** 

I know this is forum for pure issue reporting and wrong place. So, apologize for it.

**Comment by robshakir** [comment]
It's best to discuss this on openconfig/reference. There are a couple of issues already:

https://github.com/openconfig/reference/issues/42
https://github.com/openconfig/reference/issues/93

We are working to figure out the best way to define dial-out for gNMI. There isn't currently a definition for gNMI dial-out.

**Comment by robshakir** [comment]
Closing this issue in preference to the openconfig/reference issues.
