### ISSUE TITLE
gNmi Subscribe, gNmi gnxi

### ISSUE THREAD

**Issue by idefixcert** [openconfig/gnmi#47]
Is there a plan to combine gnmi subscribe of this repo and the gnxi implementation.

I you would start to implement an gnmi target, would you start at gnxi or at gnmi subscribe and add the rest?

Is there a way to use the YANG models for validation before they are stored in the cache?
Can me someone point to the right direction?

**Comment by gcsl** [comment]
That is correct.

**Comment by idefixcert** [comment]
Ok one more:
the ctree allows to store data in the tree.
If I consider to store interfaces in the tree how would that work?
How to model the path?
/interfaces/interface[name=a]/config/AdminStatus/up
/interfaces/interface[name=b]/config/AdminStatus/up
would that be the idea?
