### ISSUE TITLE
gNMI SET example

### ISSUE THREAD

**Issue by saramach** [openconfig/gnmi#48]
Folks-
This is not a bug report. But, I didn't know where to get my thought validated. I want to check if I'm using the right SET command and comply with gNMI. We are using the "protobuf.any" (structured data types mentioned in section 2.3.3 of the gNMI spec) encoding for the data.
Eg: Setting interface properties for interface "ethernet1/1/1":
```
SET request : update {
  path {
    elem {
      name: "interfaces"
    }
    elem {
      name: "interface"
      key {
        key: "name"
        value: "ethernet1/1/1"
      }
    }
  }
  val {
    any_val {
      type_url: "type.googleapis.com/openconfig.openconfig_interfaces.Interfaces.Interface"
      value: "\332\246\343\372\t&\352\366\377\215\001\002\b\001\332\201\317\305\001\017\n\rethernet1/1/1\262\272\220\233\v\003\b\376\v"
    }
  }
```

Another example, for setting up a BGP Neighbor:

```
SetRequest: replace {
  path {
    elem {
      name: "bgp"
    }
    elem {
      name: "neighbors"
    }
    elem {
      name: "neighbor"
      key {
        key: "neighbor-address"
        value: "192.168.3.1"
      }
    }
    elem {
      name: "config"
    }
  }
  val {
    any_val {
      type_url: "type.googleapis.com/openconfig.openconfig_bgp.Bgp.Neighbors.Neighbor.Config"
      value: "\202\277\260!\r\n\v192.168.3.1\302\362\321\205\v\002\b\001\222\261\275\214\v\004\b\331\370\003\272\231\366\265\016\004\b\200\370\003"
    }
  }
}
```
Could someone confirm if I'm doing this right?
Thanks for your time.

**Comment by robshakir** [comment]
Hi!

Have you seen the document describing use of protobuf in gNMI [here](https://github.com/openconfig/reference/blob/master/rpc/gnmi/protobuf-vals.md)?

To avoid duplication of the type, we introduced a `proto_bytes` field alongside the `protobuf.Any` which meant that path information would not need to be duplicated. If using the `protobuf.Any` field, then the `SetRequest` examples seem reasonable.

Cheers,
r.

**Comment by saramach** [comment]
Thanks @robshakir. 
I missed that document you pointed to. (realized it was referenced in the proto file too). Thanks for that. Is this scheme finalized? (I see the status in the doc as "Proposal").
And also, thanks for confirming the protobuf.Any part.
Thanks!
