### ISSUE TITLE
cache, gnmi update, suppressed duplicate value prevents all other updates

### ISSUE THREAD

**Issue by idefixcert** [openconfig/gnmi#52]
Hi,
I identified following problem:
If I update the cache with multiple Updates in one gNmi Notification, and one Notification has the same value as the old one, than on the following line an error is generated: 

https://github.com/openconfig/gnmi/blob/33a1865c302903e7a2e06f35960e6bc31e84b9f6/cache/cache.go#L491

and here the loop is aborted.

https://github.com/openconfig/gnmi/blob/33a1865c302903e7a2e06f35960e6bc31e84b9f6/cache/cache.go#L349-L352

I think that is not correct.

**Comment by mkhsueh** [comment]
@idefixcert - this sounds very similar to a problem fixed in https://github.com/openconfig/gnmi/commit/69c8afb615b714081c2b23ad74e9efa1934f8ad8.

Does this address your issue?
