### ISSUE TITLE
Any change causing this issue with  gnmi_cli.go? 

### ISSUE THREAD

**Issue by anzolex** [openconfig/gnmi#74]
Any change causing this issue with  gnmi_cli.go? 

../../../../../../pkg/mod/github.com/jipanyang/gnmi@v0.0.0-20180820232453-cb4d464fa018/cli/cli.go:366:15: cannot use func literal (type func([]string, *ctree.Leaf, interface {})) as type ctree.VisitFunc in argument to c.Tree.WalkSorted?

**Comment by robshakir** [comment]
Hi,

I don't seem to be able to replicate this with `1.14` and a clean `GOPATH`. What version are you running? It also seems like you're running against a fork here rather than the head version which might not have picked up changes in the calling code.

Cheers,
r.

**Comment by anzolex** [comment]
Thanks @robshakir , I switched to the to the original repo and it's working for me now.
