### ISSUE TITLE
Compilation failure due to latest commit on grpctunnel 

### ISSUE THREAD

**Issue by bhupeshkothari** [openconfig/gnmi#93]
Commit in question: https://github.com/openconfig/grpctunnel/commit/02ace152db77f34a4dac4b5fc7a06f25c2d5b847

Error: github.com/openconfig/gnmi/tunnel/tunnel.go:144:13: client.Registered undefined (type *tunnel.Client has no field or method Registered)

**Comment by jxx-gg** [comment]
apologize for the break. it is due a the recent refactor effort of the grpctunnel package. just committed a fix. please let us know if the issue still persists.
