### ISSUE TITLE
gnmi client for subscribe and gnmi server stream to kafka

### ISSUE THREAD

**Issue by babuveld** [openconfig/gnmi#96]
Hi,

Can gNMI client be used to just dynamically subscribe for sensor paths and allow gNMI server to send the telemetry data to different destination like kafka?

**Comment by colinmcintosh** [comment]
Hi @babuveld! You may want to check out [gnmi-gateway](https://github.com/openconfig/gnmi-gateway) which has the functionality to dynamically subscribe to target devices and can also send telemetry data to different destinations using Exporters. Here is a link to a pretty basic Kafka Exporter included with gnmi-gateway:

https://github.com/openconfig/gnmi-gateway/blob/release/gateway/exporters/kafka/kafka.go
