### ISSUE TITLE
Consider relocating gNxI over grpctunnel docs to reference repo

### ISSUE THREAD

**Issue by aashaikh** [openconfig/gnmi#99]
Since nearly all documentation and technical notes for gNMI / gNOI resides in the [openconfig/reference](https://github.com/openconfig/reference/tree/master/rpc) repo, can we please consider moving the grpctunnel docs in this repo (openconfig/gnmi/docs/) to the reference repo?

@jxx-gg @gcsl

**Comment by jxx-gg** [comment]
Sure. I will move them.

**Comment by aashaikh** [comment]
Fixed by #100 -- thanks Johnson!
